### ISSUE TITLE
GodsEye Check Suggestion

### ISSUE THREAD

**Issue by Simmo06** [Nort721/GodsEye#217]
GodsEye Build 34 BETA

Hello! I was wondering if you guys are adding a boatfly check anytime soon. I tested Boatfly with the anticheat, and it didn't pick it up at all. I apologize if I'm missing some configuration. But take this as a suggestion if it's not in the anticheat already! :D

**Comment by Nort721** [comment]
Well I guess we can add it but it will take some time since implementing this kind of check will require us to make big changes to a LOT of systems and checks in the plugin, I will leave the issue open until I'll have time to implement this

**Comment by Nort721** [comment]
Will be added in the recode release, since another person has submitted a request for a botfly check above I'm closing this one
