### ISSUE TITLE
[False Flag] [Feature Request] BadPackets TypeL false flag with worldguard

### ISSUE THREAD

**Issue by Officiated** [Nort721/GodsEye#234]
A bug report/issue report should contain:

1) GodsEye version
36 Beta
2) Server Version+Fork
1.13.2 Spigot 
3) ProtocolLib version
4.4.0
4) Server log
N/A
5) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster.
https://youtu.be/_drNuNOreqU
6) A very detailed description of the issue
BadPackets TypeL false flag with worldguard when attempting to break blocks that are protected.

**Comment by Nort721** [comment]
Does it happen only with tall grass or any block?

**Comment by Officiated** [comment]
Any block

**Comment by Nort721** [comment]
You are using the wrong ProtocolLib version which most likely caused the issue, I also can't seem to replicate it, install the correct ProtocolLib version from GodsEye's spigot page and let us know if the issue still exists
