### ISSUE TITLE
Badlion Client False Detection

### ISSUE THREAD

**Issue by KoxSosen** [Nort721/GodsEye#242]
A bug report/issue report should contain:

1) GodsEye 36 BETA (Latest)
2) PaperSpigot 1.12.2 (Latest)
3) ProtocolLib for 1.8.x - 1.13.x
4) There's no error in the console.
5) The issue:
6) Godseye Detects Badlion Client 1.8.9 as BadPackets TypeG and somethimes TypeD when eating an apple. It only happens when someone using Badlion.

**Comment by Nort721** [comment]
that's really wired, maybe it's related to the 1.7.10 animations mode?

**Comment by Nort721** [comment]
Just letting you know that if you wont reply to comments in about a week the issue will be closed for inactivity

**Comment by KoxSosen** [comment]
Yes, it might related to that.  I'm not sure, but might.

**Comment by Nort721** [comment]
Should be fixed at next version as we are testing and fixing any check that we found to false with that
