### ISSUE TITLE
Movement type A and H false

### ISSUE THREAD

**Issue by Kurumi78** [Nort721/GodsEye#250]
A bug report/issue report should contain:

1) Godseye 38
2) 1.16.3 Paper
3) V4.6.0-SNAPSHOT-b480
4) No stackstraces or any other potential debug info found.

6) Movement Type A and H have falsely kicked our players a couple of times.

**Comment by Nort721** [comment]
Any chance you know what was the specific action that caused the falses

**Comment by Nort721** [comment]
Can't replicate the issue, if any specific actions will be reported that triggers the checks it will be fixed, issue closed for lack of information
