### ISSUE TITLE
Impact logn jump - bypass

### ISSUE THREAD

**Issue by akosvr** [Nort721/GodsEye#253]
I was on the test server and I don't get any flags (godseye.nort721.com)

https://i.ibb.co/7XWBj3n/ezgif-3-1b0bdebe72b0.gif

If you don't keep pressing the forward button, just only when you hit the ground you are able to speed.

Have a nice day! :)

**Comment by TopRaider** [comment]
Please follow the instructions:

GodsEye version
Server version+fork
ProtocolLib version
Server log
Explanation of how to reproduce the issue

**Comment by akosvr** [comment]
I was on the test server... you can see the logs and, there is an explanation how you can reproduce it.

**Comment by Nort721** [comment]
cant't download the client, seems like its a virus anyways 99% chance the longjump will be detected by the new SpeedC check
