### ISSUE TITLE
Godseye Movement [Type: F]

### ISSUE THREAD

**Issue by Green-Sickness** [Nort721/GodsEye#255]
A bug report/issue report should contain:

1) Build 39
2) Paper 1.16.3
3) ProtocolLib version latest
4) https://pastebin.com/8PjPWTzR
5) https://streamable.com/43gahu
6) It happend when i was running and jumping

**Comment by Nort721** [comment]
We know that this check is broken, which is the reason it was disabled by default and we are working on a new check to replace that with
