### ISSUE TITLE
Killaura Type G + Autoclicker Type B

### ISSUE THREAD

**Issue by SadGhostYT** [Nort721/GodsEye#261]
A bug report/issue report should contain:

1) GodsEye version | B39
2) Server Version+Fork | Spigot 1.8.8 - GodsEye Test Server
3) ProtocolLib version | 4.5.1 Probably ( GodsEye Test Server )
4) Server log | https://imgur.com/a/eYzLMVB
5) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster. | https://youtu.be/73ZYGyiLKyI
6) A very detailed description of the issue
When holding Left Click and Right Click on Lunar Client, It has Blockhit alike animation which false flags on the Anticheat for some reason only on Sign

**Comment by Nort721** [comment]
does this happen only with Lunar client

**Comment by SadGhostYT** [comment]
Any client where you can do the blockhit thing on blocks and solid stuff where you hold both clicks.

**Comment by Nort721** [comment]
Can't remember if I fixed or not, pretty sure I did by looking at the code and I can't seem to replicate the issue
