### ISSUE TITLE
PrePlayerViolationEvent

### ISSUE THREAD

**Issue by snackmix** [Nort721/GodsEye#263]
Can you add a cancel-able PrePlayerViolationEvent that triggers before the violation is sent.
I need to use that to prevent a violation for players under certain conditions.

```
1.16.2 Paper
GodsEye Build 39 RELEASE
ProtocolLib 4.6.0-SNAPSHOT-b480
```

**Comment by Nort721** [comment]
Yup, will most likely add this next update
