### ISSUE TITLE
GodsEye Unban

### ISSUE THREAD

**Issue by Jakaboii** [Nort721/GodsEye#265]
Any chance I could get unbanned from the discord and test server? I got banned on both for reporting bypasses on the discord
![image](https://user-images.githubusercontent.com/50416254/97621485-dd58fa80-1a1a-11eb-9e38-8df4794762e4.png)
The ban reason is pretty dumb, considering I'm nowhere near capable of developing a hacked client

Discord username is Jakaboii#1373 and mc username is Jakaboii

**Comment by Nort721** [comment]
Honestly idk if you did or didn't develop a hack client on the server. and idk which method our staff used at the time to detect that, but I'm sure you didn't get banned for nothing, our very small staff team would never ban someone for no reason, in addition, your ban reason for the discord server is toxicity and trash talk and again that's a completely different ban reason you got in the test server, you want me to believe that you were false banned twice by our staff team on two different platforms?, probably not, you maybe were not developing a hacked client but the discord server ban is enough reason for me to not unban you

~ Ban appeal rejected

**Comment by BartomeuOut** [comment]
w

**Comment by Jakaboii** [comment]
@Nort721 

Could I ask how I was toxic?
If I remember correctly, I simply said something along the lines of "Spider, Jesus, smth smth, bypasses" and then I got banned.

And yes, I do think (know) that I was false banned twice and I'm pretty sure it was you, and you are simply making up a load of stuff just to make your average anticheat look above average.

I also have no idea how you could figure out if someone is developing a client or not, is it simply because I never mentioned the client name? If so, I never got a chance to, because as soon as you saw my messages, you banned me (assuming you're the one who banned me).

You can sit here and act as if I was toxic and developing clients (somehow) for the sake of making your anticheat look good and at the cost of looking like an idiot, or you can own up to not being able to take criticism and unban me.

Or maybe I am completely wrong and your staff should be taught the difference between toxicity and constructive criticism (even though I was only reporting bypasses), and the difference between "developing a client" and testing an anticheat.. which is the whole reason of a test server.
