### ISSUE TITLE
False Positives

### ISSUE THREAD

**Issue by snackmix** [Nort721/GodsEye#266]
```
GodsEye Build 40 RELEASE
ProtocolLib 4.6.0-SNAPSHOT-b480
Paper 1.16.2
```

- **InventoryActions TypeD** triggers anytime someone moves something in their inventory or click-drags to split a stack.
- **Speed TypeA** and **Fly TypeG** triggers when someone activates or flys around using a vanilla eltyra.

**Comment by Nort721** [comment]
Hey there, I strongly recommend to not enable checks that are disabled by default like Speed TypeA and Fly TypeG

**Comment by snackmix** [comment]
Good to know, I enabled all from the start, I will re-check what the defaults are and disable those.

What's the reason behind keeping them disabled?

**Comment by Nort721** [comment]
TypeA is an old check that will be replaced, Fly TypeG is experimental, also I remove InventoryActions TypeD in the next version as it's not needed anymore
