### ISSUE TITLE
onPacketReceiving Exception

### ISSUE THREAD

**Issue by snackmix** [Nort721/GodsEye#267]
```
GodsEye Build 40 RELEASE
ProtocolLib 4.6.0-SNAPSHOT-b480
Paper 1.16.2
```

https://pastebin.com/raw/Fs3c4pgv

**Comment by snackmix** [comment]
I was asked to sent you the stack trace again.
It's the same one, but here's a new paste: https://pastebin.com/raw/wv3sE8uj

**Comment by Nort721** [comment]
Try disabling BadPackets TypeE, this might stop the error from popping up

**Comment by snackmix** [comment]
That has prevented this error from appearing anymore.
Is TypeE important and something that should be fixed? If not then I assume this issue can be closed.

**Comment by Nort721** [comment]
> That has prevented this error from appearing anymore.
> Is TypeE important and something that should be fixed? If not then I assume this issue can be closed.

I'm fixing the check for the next update, disabling it is just a temporary solution
