### ISSUE TITLE
gods eye crashes with worldedit command //set and pressing space bar after

### ISSUE THREAD

**Issue by ionixxz** [Nort721/GodsEye#268]
A bug report/issue report should contain:

1) GodsEye version
2) Server Version+Fork
3) ProtocolLib version
4) Server log
5) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster.
6) A very detailed description of the issue

Hey guys i got a massive issue with godseye to make sure it isnt anything else we deleted every single plugin on the server and did a process of elimination when we install godseye on the server with running 1.16.4 we have also worldedit on the server when we run the //set command the 2nd we hit the space bar after //set it kicks us off the server but only the player who did the command the log does not show any errors
currently godseye is removed off my survival server I had my 3 devs on with me when this happened so we we running tests

there is no errors in the log at all for world edit or world guard the 2nd i deleted godseye no issues

if we removed protocollib completely from the server this deactivated godseye than it works seems godseye only is the one that causes the crash

this was never an issue in 1.16.3

but we currently have no protection on the server and are vulnerable

**Comment by Nort721** [comment]
Please fill up the info thats requested above

GodsEye version
Server Version+Fork
ProtocolLib version
Server log

Also I have just tested it, runned a 1.16.4 server and installed latest WorldEdit and GodsEye V40 and Latest ProtocolLib, typed //set and pressed space and tab, nothing happened

**Comment by ionixxz** [comment]
I have 5 servers I put it on a blank server prior and it did it I'm running
a paper server

**Comment by Nort721** [comment]
should be fixed now in the latest version
