### ISSUE TITLE
AimAssist Type B False Positive

### ISSUE THREAD

**Issue by typecek123** [Nort721/GodsEye#270]
A bug report/issue report should contain:

1) GodsEye version
Build 40
2) Server Version+Fork
This server is running CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
3) ProtocolLib version
ProtocolLib v4.5.1
4) Server log
I have disabled that so..
5) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster.
6) A very detailed description of the issue
AimAssist Type B is giving False Positive to a lot of players, even me and I do not use cheats (tested when my right were removed)

**Comment by Nort721** [comment]
Will take a loot at it while working on next update, disable AimAssist TypeB for now
