### ISSUE TITLE
Warning message

### ISSUE THREAD

**Issue by oliver11443** [Nort721/GodsEye#272]
1) GodsEye Build 40 Release
2) 1.8.8 Hyperion
3) ProtocolLib version 4.5.1
4) https://pastebin.com/ZYPzEerE

**Comment by Nort721** [comment]
Thats a ProtocolLib message, it should be nothing to worry about

**Comment by Nort721** [comment]
hmm I will have another look at this when I'll have time

**Comment by Nort721** [comment]
should be fixed in next version
