### ISSUE TITLE
False Positive Movement Type H

### ISSUE THREAD

**Issue by typecek123** [Nort721/GodsEye#274]
A bug report/issue report should contain:
GodsEye version
Build 40 Release
Server Version+Fork
Paper version git-Paper-267 1.16.4, Implementing API version 1.16.4-R0.1-SNAPSHOT
ProtocolLib version
ProtocolLib v4.5.1
4) Server log
5) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster.
6) A very detailed description of the issue
Players built soul sand lift and it kicks them for MovementType H, I saw it literally, they did nothing wrong, just were in the lift.

**Comment by Nort721** [comment]
Any chance you can make a video showing the action that causes the flags?

**Comment by typecek123** [comment]
https://www.youtube.com/watch?v=WDrbIhon8Kk

**Comment by Nort721** [comment]
Hmm I see, will make sure to fix this next version, for now, open the checks.yml file and disable Move TypeH and restart your server
