### ISSUE TITLE
Hello i want to use godseye anticheat in my skywars 1.8.8 and 1.16.4 survival it is possible?

### ISSUE THREAD

**Issue by flamingomg** [Nort721/GodsEye#275]
A bug report/issue report should contain:

1) GodsEye version
2) Server Version+Fork
3) ProtocolLib version
4) Server log
5) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster.
6) A very detailed description of the issue

**Comment by Nort721** [comment]
Yes that's possible, you can read more about GodsEye and purchase it here: https://www.spigotmc.org/resources/godseye-anticheat-advanced-detection.69595/
