### ISSUE TITLE
Boat Fly Check

### ISSUE THREAD

**Issue by KoxSosen** [Nort721/GodsEye#277]
A bug report/issue report should contain:

1) Build 40
2) Tuinity latest 1.16.4
3) Latest
5) https://cdn.discordapp.com/attachments/599887666573606923/780369735559675924/unknown.png
6) Boat fly isn't checked, meaning anyone with boatfly can easly move in survival servers, witch is a really big advantage. Please make a boat fly check

**Comment by akosvr** [comment]
It can be realy usefull. Untill the boatfly check is out I think it's the best 
temporary option.
https://www.spigotmc.org/resources/noboatfly.86016/

**Comment by Nort721** [comment]
added in Build 41
