### ISSUE TITLE
NullPointerException error

### ISSUE THREAD

**Issue by ScRauben** [Nort721/GodsEye#278]
GodsEye version : Build 40
Server Version+Fork : guardspigot 1.12.2
3) ProtocolLib version : 4.5.1
4) Server log : https://pastebin.com/0H55Dwrf
5) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster.
6) A very detailed description of the issue

**Comment by Nort721** [comment]
Is this error happens everytime you try to activate GodsEye? can you check if that happens with Paper or normal Spigot

**Comment by Nort721** [comment]
issue should be gone now, if it still happens contact our support team in discord and we will give it a deep dive check again, can't seem to replicate it though so were hoping its fixed
