### ISSUE TITLE
Many Bypasses

### ISSUE THREAD

**Issue by iazex** [Nort721/GodsEye#279]
A bug report/issue report should contain:

1) GodsEye v40
2) 1.16.3+Fork??
3) 4.6.0-SNAPSHOT-b482
4) https://hastebin.com/tukaqebevu.properties
5) Will come soon
6) Found bypasses: fly, speed, killaura, jesus, scaffold, tower

**Comment by Nort721** [comment]
You have most likely wasn't checked by GodsEye at all, you probably was opped or deoppped yourself but didn't rejoin the server before testing, I encourage you to test these cheats on out official test server and see if the bypasses also happen there if they are then its a real bypass

**Comment by Nort721** [comment]
already talked about the bypasses in the discord server (cheats flagged on the test server)
Also, I also fixed now the error that can be found in your server log
