### ISSUE TITLE
GodsEye Manual Activation

### ISSUE THREAD

**Issue by SleepyStew** [Nort721/GodsEye#280]
1) GodsEye version: Build 40
2) Server Version+Fork: 1.8.8
3) ProtocolLib version: 4.5.1
4) Server log:
12:39:47 [INFO] duels > [GodsEye] Enabling GodsEye vBuild 40 RELEASE
12:39:48 [INFO] duels > [GodsEye] activation failed!
12:39:48 [INFO] duels > [GodsEye] Your GodsEye copy is not activated for an unknown reason, please contact TopRaider or Nort721 for manual activation
12:39:48 [INFO] duels > [GodsEye] Disabling GodsEye vBuild 40 RELEASE
12:39:48 [INFO] duels > [GodsEye] has been disabled
5) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster. (Not Needed)
6) A very detailed description of the issue
As I can see from console, my version of the plugin supposedly isn't valid, but I did buy it from the official spigot website. Was wondering wether you could please manually activate it or tell me how long its ment to take to automatically activate.

Thanks!

**Comment by Nort721** [comment]
whats your spigot username?

**Comment by Nort721** [comment]
Please join the GodsEye discord server and message me on DM and send your spigot username if your copy have not been activated yet
Discord invite: https://discord.gg/gHJ8Cjx
