### ISSUE TITLE
please, you have to improve this plugin, it is very good, but needs fixes.

### ISSUE THREAD

**Issue by Palata445** [Nort721/GodsEye#281]
A bug report/issue report should contain:

1) Build 40
2) 1.16.4
3) latest
4) 
5) 
6) It marks me hacks for everything people do. but what's more, there is a lot of incidence with the elite. also in people who have a bit of lag, it marks it as if they had hacks. In short, the plugin sees for almost everything that they are hacks. climbing scaffolding, he sees it as fly.

**Comment by Nort721** [comment]
Once we implement 1.16.4 to GodsEye these falses should be solved
