### ISSUE TITLE
Scaffold Bypass ? ? ? 

### ISSUE THREAD

**Issue by DaffyDG** [Nort721/GodsEye#291]
A bug report/issue report should contain:

1) GodsEye version [ 40 ]
2) Server Version+Fork [ Paper Spigot ]
3) ProtocolLib version [ ProtocolLib for 1.8.X -> 1.15.X ]
4) Server log [ - ]
5) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster. [ Linked 7) ]
6) A very detailed description of the issue [ Linked 7) ]
7)Video - https://www.youtube.com/watch?v=p5yAcYhUp0Q

**Comment by Nort721** [comment]
Well its not a complete bypass since it did seem to fail badpackets TypeM sometimes and that would be enough to punisb the player in some cases but I do agree that this needs patching

**Comment by Nort721** [comment]
Tested the scaffold and it spams flags for a lot of checks, I contacted the guy on the distance he said that he used the wrong ProtocolLib version?

Anyhow I didn't manage to replicate the bypass on my own

**Comment by Nort721** [comment]
Will work on improving the scaffold detection in further updates
