### ISSUE TITLE
Memory leak issues

### ISSUE THREAD

**Issue by Zenya4** [Nort721/GodsEye#292]
GodsEye version: Build 40 HOTFIX 1
Server version: CraftBukkit version git-TacoSpigot-"95870a93" (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)
ProtocolLib version: 4.5.1
Server log: N/A

There seems to be a memory leak issue with regard to GodsEye. My server reaches its max ram usage very quickly after around 12 hours with GodsEye enabled.

Here is the heapdump generated with GodsEye enabled: https://prnt.sc/vxx0jl

And after disabling GodsEye temporarily via plugman: https://prnt.sc/vxx0df

It seems like some hashmaps aren't being handled properly in the plugin. I know it may seem a bit vague, but hopefully you can look into it

**Comment by Nort721** [comment]
Thos heap dumps don't tell me much, any chance you can give me a more detailed heapdump like with VisualVM or JProfiler, something that can point at a specific class?

The heapdumps you showed doesn't show any memory leak, memory usage is obviously going to be higher with GodsEye in, AntiCheats are heavy plugins, all of them anyhow will need more detailed information about it

**Comment by Nort721** [comment]
I do not find these reports as showing memory leaks, will need to do some other testings with better tools more severe results, from checking my code it seems like we are cleaning all hashmaps at some point
