### ISSUE TITLE
Kick players who don't cheat

### ISSUE THREAD

**Issue by steveq7** [Nort721/GodsEye#294]
A bug report/issue report should contain:

1) GodsEye version
Build 40 RELEASE
2) Server Version+Fork
1.16.4 Paper
3) ProtocolLib version
#483
4) Server log
Here is an example log file of that kick anti-cheat of a player who didn't cheat

  LogsCount: 1
  '1':
    Date: 4-12-2020
    Detection: INVENTORYACTIONS
    Type: TypeD
    TPS: 20.0
    Ping: 100
    PunishType: KICK

5) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster.
I do not have a video, but I saw that the player played normally and kick it suddenly and so with different players. I even entered from a multi-account and it also crashed for nothing (I didn't have cheats there)

6) A very detailed description of the issue
When I have this plugin on the server, I anti-cheat kick different players, different players who aren't cheating, who are clean. I also use 2 antycheat.
Spartan Antycheat.
There was also the same problem, but there I got a fix to the check file from the plugin creator. And he said it's because I have a Skript plugin.

**Comment by Nort721** [comment]
Please update to the latest version of GodsEye, this will help minimizing false positives

**Comment by steveq7** [comment]
> Please update to the latest version of GodsEye, this will help minimizing false positives

I downloaded and checked. Players without cheat kicks for cheats such as fly or what I sent earlier. I entered from a multi-account and also kicked me at some point, when I was running, I was just jumping and playing survival. So it's still the same as I had. I even removed 2 antycheat to see if it could be because of him, but not.

**Comment by Nort721** [comment]
I strongly recommend to not use multiple AntiCheats, the false kicks mostly likely happen because you have multiple AntiCheats on the server

**Comment by Nort721** [comment]
If you'll still have the false kicks issue when you have GodsEye on the server without other ACs here id what I recommend doing:

- use the /ge verbose command to enable verbose messages, then when you see a false suspect that gets repeated a lot, go to the checks.yml file and disable that specific check type

**Comment by Nort721** [comment]
Contact me privately on discord if you still need help handling this issue
