### ISSUE TITLE
Fix / improve killaura cancel

### ISSUE THREAD

**Issue by akosvr** [Nort721/GodsEye#297]
Hi! Please make the current killaura cancel more accourate, or for example when a player got a killaura flag block all of the hits for like 20 tick, It can be very anoying for cheaters and they gives up with cheating.

I saw a lot of anticheats how they deals with cancelling killaura, I think it can be an easy and an effective way to block killaura.

**Comment by Nort721** [comment]
Will be handeled most likely in the next hotflix, planned to be relased in the weekend hopefully
