### ISSUE TITLE
Feature request - #Advenced settings for movement cancel

### ISSUE THREAD

**Issue by akosvr** [Nort721/GodsEye#298]
### **Please let us to configure setback location.**

**Like ↓↓↓**

#Itwouldbesocool

   
 
![image](https://user-images.githubusercontent.com/29522832/103143486-4c02bd80-4717-11eb-9023-0a79d054d3b1.png)

I think you know that to. :)
Have a great day, and stay safe.

**Comment by Nort721** [comment]
Will be added in the next release

**Comment by akosvr** [comment]
Thanks!
