### ISSUE TITLE
Issue - #Nofall bug

### ISSUE THREAD

**Issue by akosvr** [Nort721/GodsEye#300]
**GE 40 hotfix 3
latest protocolib
Server version: git-Paper-342**

_Some of my players reported that it gives false positives and damages them when they fall from high into water._

Hope you can reproduce it :)
Stay safe!

**Comment by Nort721** [comment]
I can't seem to replicate the issue, please send a video or a gif or explain how exactly they replicate the issue, I tested jumping from a high place into a pool of water in 1.16.4 with GodsEye on and didn't have any issue

**Comment by akosvr** [comment]
Hi! You can just close this Issue I think :)

**Comment by Nort721** [comment]
Even though I can't seem to replicate the issue, since it seems like it happens to multiple people I am implementing something that should fix the problem
