### ISSUE TITLE
Godseye kicking legitimate players.

### ISSUE THREAD

**Issue by FO4CM** [Nort721/GodsEye#303]
A bug report/issue report should contain:

I am using GodsEye version build 40 hotfix 3

Paper version 1.16.3
ProtocolLib version ProtocolLib v4.6.0-SNAPSHOT-b483
Video: https://youtu.be/A_GWTBxoNUk?t=160
logs: https://pastebin.com/g9me0hH7

I hope this gonna help.

**Comment by Nort721** [comment]
I need to know which check type triggers the false, use /ge verbose to see check types then comment it here

**Comment by Nort721** [comment]
closed for lack of info
