### ISSUE TITLE
Riptide triggering anticheat and cancelling. Also randomly broke something and console started spamming

### ISSUE THREAD

**Issue by 22s** [Nort721/GodsEye#304]
When using riptide if the player flys for too long or flys directly upwards it flags Movement check H and cancels the movement. Also after throwing a bunch of times, at the last throw of the video it randomly allows me to riptide upwards but then starts spamming console with "Could not pass event PlayerRiptideEvent to GodsEye vBuild 40 HotFix-3
java.lang.NullPointerException: null" after that point, completely allowing me to riptide every time after that but spamming that same error. 
I am running GodsEye version Build 40 HotFix-3 on AirplaneLite for 1.16.4, I am running ProtocolLib v4.6.0-SNAPSHOT-b486.
[The server log is linked here](http://paste.endcrystal.me/paste.php?raw&id=57) 
[A video of the issue is linked here](https://youtu.be/F_ZikfkqkkE)

**Comment by Nort721** [comment]
fixed in Build 41
