### ISSUE TITLE
KillAura Type J

### ISSUE THREAD

**Issue by Lorexdx** [Nort721/GodsEye#306]
link:  https://www.youtube.com/watch?v=_9PzUaxkuSU&feature=youtu.be&ab_channel=Lorex

**Comment by Nort721** [comment]
Please provide the following information


A bug report/issue report should contain:

1) GodsEye version
2) Server Version+Fork
3) ProtocolLib version
4) Server log
5) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster.
6) A very detailed description of the issue

**Comment by Nort721** [comment]
Closed for Lack of info
