### ISSUE TITLE
False flag for use of rockets with elytra. 1.16.4

### ISSUE THREAD

**Issue by PunkMagic** [Nort721/GodsEye#307]
A bug report/issue report should contain:

1) GodsEye version - Build 40 hotfix-3
2) Server Version+Fork - 1.16.4 (Light Spigot)
3) ProtocolLib version - 4.5.1
4) Server log
5) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster.
6) A very detailed description of the issue - While a player uses rockets and an elytra to fly fast, it false flags them for speed.

**Comment by Nort721** [comment]
I can't seem to replicate the issue, please provide what type of speed is falsing, you can do that by using the /ge verbose command and replicating the issue

**Comment by Nort721** [comment]
can't seem to replicate the issue
