### ISSUE TITLE
Anti Knockback bypass!

### ISSUE THREAD

**Issue by xXSwainXx** [Nort721/GodsEye#308]
A bug report/issue report should contain:

1) GodsEye vBuild 40 HotFix-3
2) CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
3) ProtocolLib v4.5.1
4) Server log - Nothing
5) 
6) On our network where there is the game mode Waterfight I noticed after a test. if I activate Anti Knockback and when I swim in the water up and down that the Anti Knockback is let through it happens purely nothing because he always swims up and down you could fix it because it has for this game mode otherwise simply with anti Knockback a very big advantage!

**Comment by Nort721** [comment]
A horizontal velocity check is in development to solve that problem
