### ISSUE TITLE
#Trident with riptide is unusable

### ISSUE THREAD

**Issue by akosvr** [Nort721/GodsEye#309]
### GE 40 hotfix 3
**ProtocolLib 4.5.1
Server version: git-Paper-342**

_Trident with riptide triggers Movement H, and Fly C check_
![ezgif-3-e8489b22596c](https://user-images.githubusercontent.com/29522832/103442752-5e21b600-4c59-11eb-85b1-749a691382f2.gif)
![ezgif-3-97718c8db92e](https://user-images.githubusercontent.com/29522832/103442786-932e0880-4c59-11eb-9142-20318d1f60b9.gif)

Have a great day, stay safe!

**Comment by Nort721** [comment]
should be fixed in Build 41
