### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Porkason** [Nort721/GodsEye#311]
A bug report/issue report should contain:

1) Build 40 HotFix-3
2) 1.16.3 Paper
3) 4.5.1
4) Server log
5) https://pastebin.com/CKCuQ2qr
6) It happened when i switched between items (no cheat)

**Comment by Nort721** [comment]
You are most likely using the wrong version of ProtocolLib

**Comment by Nort721** [comment]
Please try downloading ProtocolLib for 1.16.X from GodsEye's spigot page
