### ISSUE TITLE
NoKnockback bypass Again

### ISSUE THREAD

**Issue by xXSwainXx** [Nort721/GodsEye#314]
1.) GodsEye vBuild 40 HotFix-4
2.) CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
3.) ProtocolLib v4.5.1
4.) Server log - Nothing
4.) same problem -> https://github.com/Nort721/GodsEye/issues/308
5.) On our network where there is the game mode Waterfight I noticed after a test. if I activate Anti Knockback and when I swim in the water up and down that the Anti Knockback is let through it happens purely nothing because he always swims up and down you could fix it because it has for this game mode otherwise simply with anti Knockback a very big advantage!

Video: https://youtu.be/VToPilSr2-A

**Comment by Nort721** [comment]
There is no need to open a new issue for the same problem

**Comment by Nort721** [comment]
We are working on a Horizontal Velocity check, horizontal velocity checks are very hard so its going to take some time until it will be production ready, but we are working on it, until then you'll have to do with the knockback and vertical velocity check (Velocity TypeA)
