### ISSUE TITLE
False flag Reach type: A

### ISSUE THREAD

**Issue by Lorexdx** [Nort721/GodsEye#315]
1)GodsEye Build 40 HotFix-4
2) 1.8.9
3) ProtocolLib 4.5.1
4) Server log - nothing
5) https://youtu.be/Eq4tbV3nygM
6) by constantly hitting the head there is false reach information

**Comment by Nort721** [comment]
Please provide the punishment log of when you got punished in that video, which can be found at plugins/GodsEye/logs

**Comment by Lorexdx** [comment]
https://pastebin.com/NgpiDSQC

**Comment by Nort721** [comment]
we recommend not set max flags to 1, keep it on around 20 - 30 to get more accurate punishment results also don't set the max reach to 3.0, make sure to set it to 3.15 at least, if you configure it like that or just use the default configuration for that check you shouldn't experience false bans
