### ISSUE TITLE
KnockBack doesn't work

### ISSUE THREAD

**Issue by Lorexdx** [Nort721/GodsEye#316]
1)GodsEye Build 40 HotFix-4
2) 1.8.9
3) ProtocolLib 4.5.1
4) Server log - nothing
5) https://youtu.be/LgGbpjO8T8E
6 )When I hit a player anti-cheat doesn't notify me

**Comment by Nort721** [comment]
Please do not post multiple issue reports of the same issue, one report per issue is enough
