### ISSUE TITLE
KnockBack doesn't work again

### ISSUE THREAD

**Issue by Lorexdx** [Nort721/GodsEye#317]
1)GodsEye Build 40 HotFix-4
2) 1.8.9
3) ProtocolLib 4.5.1
4) Server log - nothing
5) https://youtu.be/o_lZ0p9pgmA
6) if the player is standing at the ladder, even if he is not at the ladder and it has antiknocback, anti cheat doesn't notify me

**Comment by Nort721** [comment]
Please do not post multiple issue reports of the same issue, one report per issue is fine
