### ISSUE TITLE
False flag AutoClicker type A

### ISSUE THREAD

**Issue by Lorexdx** [Nort721/GodsEye#318]
1)GodsEye Build 40 HotFix-4
2) 1.8.9
3) ProtocolLib 4.5.1
4) Server log - nothing
5) https://youtu.be/UwlKmZMjZMM
6) the fake message comes after hitting and backing off

**Comment by Nort721** [comment]
please provide the punishment log from that video, also you shouldn't punish the player for one flag

**Comment by Lorexdx** [comment]
https://pastebin.com/NgpiDSQC

**Comment by Nort721** [comment]
hey there, seems like you have something on your server or in the client you use that causes you to double-click, I'd recommend checking the client you use,

it just doesn't seem to be an issue on our side, also it doesn't happen to anyone else, if you still have this you should disable the AutoClicker TypeA check-in checks.yml for now
