### ISSUE TITLE
Sigma Fly doesn't reset position!

### ISSUE THREAD

**Issue by BlauToad** [Nort721/GodsEye#321]
1) GE: Build 40 HotFix-4
2) Spigot 1.16.5
3) ProtocolLib v4.5.1
4) Nothing in the server log
5) First Picture: I do not move anymore
   Second Picture: I rotated!
![image](https://user-images.githubusercontent.com/53124247/104844549-278ea100-58d1-11eb-971f-20aaaa22ea6c.png)
![image](https://user-images.githubusercontent.com/53124247/104844589-64f32e80-58d1-11eb-95ad-30e52d6692c0.png)
{ignor the scoreboard it's from my game :)}
6) I use Sigma5 Fly and do not move. No verbose! As soon as I move it just spamms Typ A and G and D **but it dosen't reset my position!**

**Comment by Nort721** [comment]
Please send here a pastebin of your checks.yml file

**Comment by BlauToad** [comment]
https://pastebin.com/CPpzLQAp

**Comment by Nort721** [comment]
I have implemented a fix, also you need to reset your checks.yml file

**Comment by BlauToad** [comment]
oh I'm sorry I have updated the checks,yml and now its working! I'm so sorry.
