### ISSUE TITLE
I paid but received nothing

### ISSUE THREAD

**Issue by DadOfHell** [Nort721/GodsEye#325]
I paid but received nothing

paypal mail : paypal@rykcraft.fr

**Comment by Nort721** [comment]
Hey there, your payment is on hold, meaning paypal decided to delay it, meaning the money is not on your side and also not on my account, its at paypals control

Normally the money will be released after 24 - 48 hours, if after this amount of time you still didnt get access comment on this issue again

**Comment by DadOfHell** [comment]
![image](https://user-images.githubusercontent.com/61395517/105025939-45cddb80-5a4e-11eb-8d4b-7ca16c7d548f.png)
for my it ok

**Comment by Nort721** [comment]
![Screenshot_20210119-142658_PayPal.jpg](https://user-images.githubusercontent.com/24839815/105034638-6f90fd80-5a62-11eb-9346-f72c791b13e3.jpg)

**Comment by Nort721** [comment]
I cant do anything about it until the payment will be released

**Comment by DadOfHell** [comment]
Ok, thank you very much for your quick response

**Comment by Nort721** [comment]
Your payment has been received and spigot gave you access automatically

**Comment by DadOfHell** [comment]
Yes it ok i have your plugin, Best support ever <3

**Comment by Nort721** [comment]
👍👍👍
Feel free to also contact us on our discord server if you need any more help
