### ISSUE TITLE
Future fly bypass (Without flyA check) / FlyA falses on slabs

### ISSUE THREAD

**Issue by akosvr** [Nort721/GodsEye#326]
A bug report/issue report should contain:

1) GodsEye 40 hf4
2) 1.16.4 paper
3) ProtocolLib latest
 
There is a fly bypass in future, only the experimental checks catches is, but fly A gives falses on slabs in 1.16

I didn't buy this cheat so I can't send you a video, I saw on my server some people fly with that client.

**Comment by akosvr** [comment]
The real issue is TypeA fly falses on 1.16.4 slabs

**Comment by Nort721** [comment]
are you sure you are on Build 40 HotFix-4 ?

**Comment by Nort721** [comment]
also are you sure you are on 1.16.4 and not 1.16.5?

**Comment by akosvr** [comment]
Yeah, it was that. Im sure.

**Comment by Nort721** [comment]
should be fixed in Build 41
