### ISSUE TITLE
New powerfull check that will detect immediately all the bhops and reverse kb 

### ISSUE THREAD

**Issue by crafticat** [Nort721/GodsEye#327]
It will detect if the player change direction when in mid air.
I know there is speed type b but it takes  a lot of time to ban and it doesn't detect it when fighting.

**Comment by Nort721** [comment]
There are lots of situations in legit Minecraft gameplay that can allow you to change direction in mid-air, however, the basic concept is known, we are already working on checks that could help detect that in the future

**Comment by crafticat** [comment]
Ok nice.
