### ISSUE TITLE
Godseye GeyserMc 

### ISSUE THREAD

**Issue by Pikaronga** [Nort721/GodsEye#329]
IT doesn't work. It doesn't ignore bedrock players. 

1) Build 40 HotFix-4
2) 1.16.4 Paper
3) The recommended from Godseye Spigot. 

It flags bedrock players and kicks them even tho it's supposed to ignore them.

**Comment by Nort721** [comment]
Dejavu has released a fork to GodsEyeGeyserMC and it now works: https://github.com/TheDejavu/GodsEyeGeyserMC
just install it along side GodsEye and bedrock players won't be falsely flagged anymore
