### ISSUE TITLE
Need help activating GodsEye

### ISSUE THREAD

**Issue by GoldXR** [Nort721/GodsEye#330]
Hey I was wondering how I activate GodsEye because like nothing works when I try to activate it.

**Comment by Nort721** [comment]
Your copy should be activated now if you try to restart your server, if it still doesn't work comment here the link to your spigot profile page

**Comment by Nort721** [comment]
Contact me on the GodsEye discord server if you are still having any issues with activation
invite: https://discord.gg/gHJ8Cjx

**Comment by GoldXR** [comment]
okay, thanks. It's all working now
