### ISSUE TITLE
Jump boost false flags

### ISSUE THREAD

**Issue by crafticat** [Nort721/GodsEye#332]
A bug report/issue report should contain:

1) GodsEye version - latest
2) Server Version+Fork - foxspigot 1.8.9
3) ProtocolLib version latest
5) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster. - I am not able to sorry
6) A very detailed description of the issue - When using a jump boost and moving after some time you will start flaging speed type b and after like 1 or 3 min you will prob will get banned.

**Comment by Nort721** [comment]
I have recoded the check, it still will be experimental but from my testing, it seems table right now and seems like it doesn't false with jump boost now

**Comment by crafticat** [comment]
Will we get it in the new update?

**Comment by Nort721** [comment]
fixed in Build 41

**Comment by crafticat** [comment]
Now speed type b doesnt detect strafe
at all
