### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by typecek123** [Nort721/GodsEye#333]
A bug report/issue report should contain:

1) GodsEye version
Build 40-Hotfix -4
2) Server Version+Fork
git paper 444-1.16.5
3) ProtocolLib version
name: ProtocolLib
version: 4.5.1
4) Server log
https://paste.hostify.cz/?9215177db242fee3#69yjucMd9VWrLaCmULhzmPL4F8vTv94eps4T8wib1GZp
https://paste.hostify.cz/?3496859d8192e5be#AcTz4X9pQcvszt1iXr9U3WffRQtqqqqGjQ5mkebbwS4Y
5) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster.
6) A very detailed description of the issue
When testing this Anticheat this error popped up in my console.

**Comment by Nort721** [comment]
Try downloading ProtocolLib from here and restart your server: https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/
