### ISSUE TITLE
Sigma 5 InvMove

### ISSUE THREAD

**Issue by BlauToad** [Nort721/GodsEye#335]
A bug report/issue report should contain:

1) GodsEye Build 41
2) Server Spigot 1.16.5
3) ProtocolLib v.4.5.1
4) Server log: nothing
5) https://user-images.githubusercontent.com/53124247/105986030-9ec7f000-609c-11eb-885e-092500fa57ab.mp4
6) Just enable InvMove and you can move with your Inv open

**Comment by Nort721** [comment]
well I did some investigating and seems like this InvMove disables the InventoryOpenAdvancment packet, now the client doesn't send any packet to the server when the player opens his personal inventory meaning anti-cheats doesn't actually any way to know if the player has opened his personal inventory unless it uses the InventoryOpenAdvancment packet which GodsEye does, however, seems like sigma have disabled this packet, meaning there is pretty much no way of patching this InvMove bypass expect checking if the player is clicking his personal inventory and moving which I will work on implementing in future updates, this kind of patch would only detect the player if he walks with the inventory open and he is clicking a slot in it, which should make the cheat effectively useless

thanks for the report!
