### ISSUE TITLE
Now speed type b doesnt detect strafe at all

### ISSUE THREAD

**Issue by crafticat** [Nort721/GodsEye#336]
A bug report/issue report should contain:

1) GodsEye version - latest
2) Server Version+Fork - foxspigot 1.8.9
3) ProtocolLib version -latest
4) Server log - doesnt matter
5) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster. Cant sorry
6) A very detailed description of the issue
Ok you updated speed type b and now it doesnt detect strafe at all and this is a really big thing for me I really need that check.
You can make a new check that will detect strafe or fix speed type b

**Comment by Nort721** [comment]
we are reimplementing the older Speed TypeB check in the next version, so that should solve that
