### ISSUE TITLE
CPU overload 

### ISSUE THREAD

**Issue by DadOfHell** [Nort721/GodsEye#337]
1) GodsEye version 

Last

2) Server Version+Fork

1.16.4

3) ProtocolLib version

Vesion for god eyes 

4) Server log

Nothing in log

5) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster.

Forget to take a screen

6) A very detailed description of the issue

The plugin lags the CPU of the server as soon as there are more than 4 players I will remove all the plugins and it is yours which creates an overload of the CPU given the price of it is shameful and very frustrating

not to mention the false positives of Nofall, Reach, Speed

**Comment by haloflooder** [comment]
I would suggest that you take a spark sampler/timings of your server to see where the lag is coming from.

I run 100+ player servers and godseye is the least of our problem when it comes to lag. Currently also running it on a 1.13 server with 20tps at 100~ players.

You can use https://www.spigotmc.org/resources/spark.57242/ and do `/spark sampler --start --timeout 120` and post a link here
or
Use timings via `/timings report` and leave it on for a minute or two and then do `/timings paste` then paste the link here.

**Comment by Nort721** [comment]
I agree with Haloflooder, will need timings and generally more information, its hard for me to believe that GodsEye is fully resposible to the lag problem that you are having, its most likely that the problem comes from somewhere else
