### ISSUE TITLE
Random Error with Player movment

### ISSUE THREAD

**Issue by 0x-k** [Nort721/GodsEye#338]
1) Build 42
2) Spigot 1_8_R3
3) ProtocilLib for 1.8-1.15
4) https://pastebin.com/KyUwKdW1
5)
6) This is some random error that occurs when players move sometimes.Not too sure why this happens, but sometimes on player move events (literally sometimes when a player moves), there's an error that occurs, and as you can imagine, it spams the shit out of the console. It looks like it's the same error each time though - caused from an IndexOutOfBoundsException as through the following:
Caused by: java.lang.IndexOutOfBoundsException: Index: 1065881069, Size: 21
Essentially trying to access the 1065881069th item in a list that only has 21 items. Once again, not actually sure when or why it occurs.

**Comment by Nort721** [comment]
let us know if the issue if this happens in the next version
