### ISSUE TITLE
Missing Chunks when loading in

### ISSUE THREAD

**Issue by 0x-k** [Nort721/GodsEye#339]
1) Build 42
2) Spigot 1_8_R3
3) ProtocilLib for 1.8-1.15
4) https://pastebin.com/QfudL02g
5) 
6) When the game begins and teleports players into the map, some players will spawn in missing chunks. This is a problem I've also experienced on Mineplex. The chunk appears for some players and not others. If the players are in this missing chunk, they cannot see anything (and are also unable to move or pearl out). This is very inconsistent, as it sometimes happens and sometimes doesn't. I can tell when it happens and when it doesn't by looking at the console as it generates a massive error.

I've sectioned out the chunk from the logs related to this issue. There's a few repeats but from what I can see it's these highlight things:
1. "Asynchronous entity world add!"
2. "java.lang.IllegalArgumentException: Cannot measure distance between Parkour City and Parkour City"

Parkour City is the name of a map/world btw

**Comment by Nort721** [comment]
seems like you were not using Build 42 when getting this error

**Comment by Nort721** [comment]
should be fixed in the next version
