### ISSUE TITLE
Packet Issue

### ISSUE THREAD

**Issue by 0x-k** [Nort721/GodsEye#340]
1) Build 42
2) Spigot 1_8_R3
3) ProtocilLib for 1.8-1.15
4)
5)
6) Players are kicked for message "You are sending too many packets." We aren't sure what is causing this, but it's happened since the anti-cheat implementation. And it seems like I'm the only person this has happened to so far. After doing some research, the resolution is to set two fields in the ViaVersion plugin config to -1 (to disable); but it seems like it's not recommended. This thread in particular outlines it: https://www.spigotmc.org/threads/emergency-you-are-sending-too-many-packets.241663/

**Comment by crafticat** [comment]
It happens to me too.

**Comment by Nort721** [comment]
I cant see how this would be related to GodsEye, but mostly would happen to you if you use hacked clients, and yeah you probably should increase the amount of packets that viaversion allows or disable the limitation completly in the ViaVersion config like they explain to you in the thread, but well I'll look into it

**Comment by Nort721** [comment]
Hey there, are you still experiencing this issue?
