### ISSUE TITLE
Idea for a cool add 1 for your great anti cheat

### ISSUE THREAD

**Issue by crafticat** [Nort721/GodsEye#342]
That you can change the godseye command to a custom command like from /ge to /ac 
I think this will be a really cool add that people will really like.

**Comment by Nort721** [comment]
Unfortunately, I'm pretty sure that making the command strings configurable would not be supported by Spigot, in addition, you'll need to edit plugin.yml if it would even work, and we prefer not asking to edit plugin.yml and config.yml in addition it could make customer support more complicated and generally make things confusing
