### ISSUE TITLE
Ping false bans

### ISSUE THREAD

**Issue by crafticat** [Nort721/GodsEye#345]
A bug report/issue report should contain:

1) GodsEye version - latest 
2) Server Version+Fork - foxspigot 1.8.9
3) ProtocolLib version - latest
4) Server log - None
5) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster. - I dont have sorry
6) A very detailed description of the issue - When some one is really lagy like more then 1300 ping, After some time he will get banned for example (And I know he is not cheating)
bb02fcd9-bae0-407b-ab3f-b70d7ef7434b:
  LogsCount: 1
  '1':
    Date: 7-2-2021
    Detection: AIMASSIST
    Type: TypeB
    TPS: 20.0
    Ping: 1766
    PunishType: BAN
    CPS: 0
    reach: 3282.4013671875

**Comment by Nort721** [comment]
Disable AimAssist TypeB in checks.yml and restart your server for now, also you probably dont want to have players with above 1000ms on your server

In addition try using the /ge ping name command, if the players normal ping and GodsEye ping have a big difference between them then they are probably ping spoofing therefore hacking and not really lagging
