### ISSUE TITLE
Ge logs doesnt work for me.

### ISSUE THREAD

**Issue by crafticat** [Nort721/GodsEye#346]
A bug report/issue report should contain:

1) GodsEye version - latest
2) Server Version+Fork - foxspigot 1.8.9
3) ProtocolLib version - latest
4) Server log - https://pastebin.com/Kirdb7gq
5) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster. - cant
6) A very detailed description of the issue - When I try to do /ge logs swoj (for example) It gives me that error

**Comment by Nort721** [comment]
hey there, please send here a pastebin of the logs file that you tried to load with the /ge logs command

**Comment by crafticat** [comment]
https://pastebin.com/Kirdb7gq

**Comment by crafticat** [comment]
And it happens only when the player is not online

**Comment by Nort721** [comment]
Should be fixed in Build 45, if it still happens in it let me know and I will reopen this issue
