### ISSUE TITLE
Speed Type B False Positive

### ISSUE THREAD

**Issue by typecek123** [Nort721/GodsEye#347]
A bug report/issue report should contain:

1) GodsEye version
Build 42
2) Server Version+Fork
1.16.5 PaperSpigot 467
3) ProtocolLib version
4.6.0
4) Server log
5) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster.
![2021-02-12_20 02 52](https://user-images.githubusercontent.com/74290177/107811036-d9ed4300-6d6d-11eb-9df9-abc3bf3a3b78.png)

6) A very detailed description of the issue
Player is getting bugged when running, speed type b. I know him very well and I believe him. No stuff in console.

**Comment by Nort721** [comment]
We are reverting to the old speed TypeB check next update, it would most likely show more stable results, but know that Speed TypeB is an experimental check so you might want to disable speed typeb specifically
