### ISSUE TITLE
over 500 ping ban my players

### ISSUE THREAD

**Issue by crafticat** [Nort721/GodsEye#351]
A bug report/issue report should contain:

1) GodsEye version - lastest
2) Server Version+Fork - 1.8.9 foxspigot
3) ProtocolLib version - lastest
4) Server log - none
5) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster.
6) A very detailed description of the issue
Today I played with my friends we were laging and 70% got banned (for killaura and some times for aim assist and sometimes movement)
when we were really lagy. Can you please add an option that you can enable on the config fill that players will more then 500 ping that are not ping spoofing will not get detected.

**Comment by crafticat** [comment]
Nvm we got banned only for aim assist type e

**Comment by Nort721** [comment]
Great then you can just disable it
