### ISSUE TITLE
Olds ver doesnt work

### ISSUE THREAD

**Issue by crafticat** [Nort721/GodsEye#353]
Hello I should like to use the oldest ver of godeye because they have less false flags and an strafe check can you please fix them.

**Comment by crafticat** [comment]
Not the oldest an old ver.

**Comment by Nort721** [comment]
We are aware of this issue, and are working towards fixing it, also we plan to returning the older Speed TypeB check

**Comment by crafticat** [comment]
Sounds good :)

**Comment by crafticat** [comment]
How much time will it take that the old ver will work? just wandering

**Comment by Nort721** [comment]
> How much time will it take that the old ver will work? just wandering

can take some time, I returning the old Speed TypeC check though

**Comment by Nort721** [comment]
they should work now if they still ask for help in the discord server
