### ISSUE TITLE
Killaura tpye g false

### ISSUE THREAD

**Issue by crafticat** [Nort721/GodsEye#354]
A bug report/issue report should contain:

1) GodsEye version latest 
2) Server Version+Fork foxspigot 1.8.9
3) ProtocolLib version latest 
4) Server log
5) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster.
6) A very detailed description of the issue
When you are stuck in a ghost block it will ban.

**Comment by Nort721** [comment]
recoded the check to a new one, the new one should be more stable now
