### ISSUE TITLE
Auto clicker false

### ISSUE THREAD

**Issue by crafticat** [Nort721/GodsEye#356]
A bug report/issue report should contain:

1) GodsEye version - latest
2) Server Version+Fork - 1.8.9 foxspigot
3) ProtocolLib version - latest
4) Server log - none
5) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster.
6) A very detailed description of the issue
When you butterfly click 14 - 16 cps with butter fly clicking on (in the check.yml)
it still bans you for auto clicker type a

**Comment by Nort721** [comment]
Did you restart your server after enabling allow butterfly clicking in checks.yml, also you made sure after that, that the checks.yml file didn't get reset?

**Comment by Nort721** [comment]
were removing the allow butterfly clicking setting from checks.yml, from now on you'll be able to configure the max cps and if you wanna to allow butterfly clicking on your server you'll need to enable verbose and disable the AutoClicker checks that false for it, as butterfly clicking has a lot of tactics and pretty much breaks game logic
