### ISSUE TITLE
[Netty Epoll Server IO #0/ERROR]: [GodsEye]

### ISSUE THREAD

**Issue by EchocallingEarth** [Nort721/GodsEye#360]
A bug report/issue report should contain:

1) GodsEye AntiCheat | Advanced Detection Build 43 R3 (HotFix)
2) Paper 1.16.5-508
3) ProtocolLib 4.6.0 #498
4) [https://pastebin.com/E65nArAA](url)
5) NA
6) Full error provided above.

**Comment by EchocallingEarth** [comment]
And again but now Netty Epoll Server IO #2/ERROR
Figured it is still part of the fixed issue from before that is still awaiting attention so just added it here.

https://pastebin.com/XaNq3fdW

**Comment by Nort721** [comment]
honestly that's a pretty weird error, hard to pinpoint, I change some code where I believe it might be the source of the error, so if you'll still have it after updating to the next version let us know and we will reopen the issue
