### ISSUE TITLE
GodsEye packet error

### ISSUE THREAD

**Issue by TheLeCrafter** [Nort721/GodsEye#361]
A bug report/issue report should contain:

1) Latest Version (GodsEye Build 43 R3 (Hotfix))
2) Latest PaperSpigot version for Minecraft 1.8.8
3) 4.6.0
4) https://pastebin.com/jn8UeRQF
5) No video/screenshots available
6) I have no idea when this error is thrown. I have tested it with different active hacks and even without hacks and this error happened without any message in game. I'll try to add as much detail as possible, but I am unsure how this error occurs.

**Comment by EchocallingEarth** [comment]
And again but now Netty Epoll Server IO #2/ERROR
Figured it is still part of the fixed issue from before that is still awaiting attention so just added it here.

https://pastebin.com/XaNq3fdW

**Comment by Nort721** [comment]
I've implemented a fix for that, not a 100% sure if that fully fixed it though since I can't seem to replicate the issue, if it still happens in the next version, contact us on discord and we will reopen the issue
