### ISSUE TITLE
And now we have NullPointerException

### ISSUE THREAD

**Issue by EchocallingEarth** [Nort721/GodsEye#362]
A bug report/issue report should contain:

GodsEye AntiCheat | Advanced Detection Build 43 R3 (HotFix)
Paper 1.16.5
ProtocolLib 4.6.0 #498
[https://pastebin.com/7ua4V5Lr](url)
NA
Full error provided above.

**Comment by Nort721** [comment]
Hopefully fixed for next version, could fully verify the fixed as I didn't manage to replicate the error, should be fixed though
