### ISSUE TITLE
Speed type c false

### ISSUE THREAD

**Issue by crafticat** [Nort721/GodsEye#364]
A bug report/issue report should contain:

1) GodsEye version - 44
2) Server Version+Fork - foxspigot 1.8.9
3) ProtocolLib version - the one from godseye spigot page
4) Server log
5) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster.
6) A very detailed description of the issue
Ok so if you have speed 2 and you jump and run it some times false. And yes sometimes it bans you

**Comment by Nort721** [comment]
Should be fixed in Build 45, if it still happens let me know and I will reopen this issue
