### ISSUE TITLE
AutoClicker work perfectly

### ISSUE THREAD

**Issue by Saharo4eks** [Nort721/GodsEye#369]
A bug report/issue report should contain:

1) GodsEye version: Build44 
2) Server Version+Fork: Purpur 1.16.5 #1048
3) ProtocolLib version: 4.6.0
4) Server log: - 
5) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster: https://imgur.com/a/s5RjP4T
6) A very detailed description of the issue: Aristoris v367

**Comment by Nort721** [comment]
There is a reason the blocked hacks list in the GodsEye page doesnt just say "AutoClicker" but says "Types of AutoClicker"

GodsEye has checks in place to detects bugs in autoclickers and Badly made ones, it also has some statistical analysis checks that are trying yo detect more advanced ones, but its impossible to detect every autoclicker in every clients, at least to the well made ones

You cant expect to have autoclicker detected like you would expect speed or fly, we do attempt to detect as many as possible, but unfortunatly it would be impossible to detect all of them, at least not in a budget anticheat, never the less will attempt the patch this one, cant promise anything though

**Comment by Saharo4eks** [comment]
> There is a reason the blocked hacks list in the GodsEye page doesnt just say "AutoClicker" but says "Types of AutoClicker"
> 
> GodsEye has checks in place to detects bugs in autoclickers and Badly made ones, it also has some statistical analysis checks that are trying yo detect more advanced ones, but its impossible to detect every autoclicker in every clients, at least to the well made ones
> 
> You cant expect to have autoclicker detected like you would expect speed or fly, we do attempt to detect as many as possible, but unfortunatly it would be impossible to detect all of them, at least not in a budget anticheat, never the less will attempt the patch this one, cant promise anything though

Have you even watched the video? I didn't just choose the clicker speed - 20CPS. The whole point is that no one will click on mobs so quickly, so at least you should add a CPS limiter.

**Comment by Nort721** [comment]
GodsEye does have a CPS limiter, according yo how Minecraft is coded 20 is the max CPS thats possible without double clicking (which only happens with badly made autoclickers or clicking methods that are not legit on most servers) which is why GodsEyes CPs limiter is coded to allow up to 20 cps, if you set an autoclicker to above 20 and didnt flag then you mostly likely didnt click above 20 according to the server side
