### ISSUE TITLE
Velocity check's false

### ISSUE THREAD

**Issue by Saharo4eks** [Nort721/GodsEye#370]
A bug report/issue report should contain:

1) GodsEye version: Build44
2) Server Version+Fork: Purpur 1.16.5 #1048
3) ProtocolLib version: 4.6.0
4) Server log: -
5) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster: https://imgur.com/a/vO9jN7G
6) A very detailed description of the issue: The check works fine when the player with "Velocity" enabled is higher than the player who is hitting it. But as soon as they get to the same height, the anti-cheat doesn't care.

**Comment by crafticat** [comment]
I think the ac doesn't detect that because you are near a block try to remove the block that is near you.
Btw I am not stuff but I think that was the problem

**Comment by Nort721** [comment]
Indeed try this when not standing bside of a block, GodsEye makes the knockback check way more sensitive when you have blocks around you since they can affect your knockback
