### ISSUE TITLE
ClickTP

### ISSUE THREAD

**Issue by Saharo4eks** [Nort721/GodsEye#371]
A bug report/issue report should contain:

1) GodsEye version: Build44
2) Server Version+Fork: Purpur 1.16.5 #1048
3) ProtocolLib version: 4.6.0
4) Server log: -
5) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster: https://imgur.com/a/mo8BW5D
6) A very detailed description of the issue: Even if this function is not stated in the anti-cheat initially, but to allow teleports throughout the map is shameful for any anti-cheat. This urgently needs to be fixed!

**Comment by Nort721** [comment]
I want you to try this on our official test server, record it and comment the link here

**Comment by Saharo4eks** [comment]
> I want you to try this on our official test server, record it and comment the link here

https://imgur.com/a/uZIJewz

**Comment by Nort721** [comment]
Seems like you are flagging speed TypeB, you can try reducing speed prevention flags so after one or two teleports it would setback for every flag, therefore will teleport the playet back for every teleport that flags, as a temporary solution 

will make sure to make a more propper check to patch that better as soon as possible

**Comment by Saharo4eks** [comment]
Through tests, it was found that Movement typeH is able to detect this teleport, and NoFall TypeB also helps it a little when you teleport from high buildings. But the problem will remain at small distances, about 5-6 blocks. At this stage, the anti-cheat does not see the teleport at all. And this is still a big problem, because players can safely teleport through walls.
https://imgur.com/a/H19eIOZ

**Comment by Saharo4eks** [comment]
> Seems like you are flagging speed TypeB, you can try reducing speed prevention flags so after one or two teleports it would setback for every flag, therefore will teleport the playet back for every teleport that flags, as a temporary solution
> 
> will make sure to make a more propper check to patch that better as soon as possible

Through tests, it was found that Movement typeH is able to detect this teleport, and NoFall TypeB also helps it a little when you teleport from high buildings. But the problem will remain at small distances, about 5-6 blocks. At this stage, the anti-cheat does not see the teleport at all. And this is still a big problem, because players can safely teleport through walls.
https://imgur.com/a/H19eIOZ

**Comment by Nort721** [comment]
patched in Build 45
