### ISSUE TITLE
Killaura/AimAssist Bypass ? ? ?

### ISSUE THREAD

**Issue by DaffyDG12** [Nort721/GodsEye#373]
Test Server!

Killaura - https://www.youtube.com/watch?v=yiaJ-QTjZtc
AimAssist - https://www.youtube.com/watch?v=xBuMWnkY8Ac

**Comment by DaffyDG12** [comment]
Killaura - It also works on vulcan and spartan

**Comment by Nort721** [comment]
You are flagging Move TypeA for the killaura, thats not a false positive its an actual detection, whats the bypass here
