### ISSUE TITLE
Scaffold Bypass ? ? ?

### ISSUE THREAD

**Issue by DaffyDG12** [Nort721/GodsEye#374]
Test Server !

Scaffold - https://www.youtube.com/watch?v=4TKclmJlalU

**Comment by Saharo4eks** [comment]
I confirm that Scaffold is detected very poorly, but I was already too lazy to post it here.

**Comment by DaffyDG12** [comment]
It also works on vulcan and spartan

**Comment by DaffyDG12** [comment]
![Capture111](https://user-images.githubusercontent.com/81573671/112884500-a0378800-90e0-11eb-9e61-e52aedbdbdcb.PNG)

**Comment by Nort721** [comment]
> I confirm that Scaffold is detected very poorly, but I was already too lazy to post it here.

Did you found any scaffold bypasses?

**Comment by Nort721** [comment]
I will most likely end up closing this issue as people can indeed bridge like that legitimately some can speed bridge faster then that, therefore this doesnt seem like it gives a big enough sugnificant advantage over other players

Pretty much like the Vape V4 Legit scaffold situation, this doesnt like something thats accurately detectable, I will analys it however just to be sure
