### ISSUE TITLE
False positives [FP]

### ISSUE THREAD

**Issue by bG9sIHVyIGhvbW8** [Nort721/GodsEye#376]
1) **GodsEye version**
Took place in testing server

2) **Server Version+Fork**
Took place in testing server

3) **ProtocolLib version**
Took place in testing server

4) **Server log**
Took place in testing server

5) **We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster.**
[Here](https://mega.nz/file/r9pmVQYJ#NPC6l6obOwYClGjp_oaYgDkiKktq8n7Nrbd7mZ0cVm8) is the video file, in the recording I was on client version 1.12.2. I uploaded it to mega.nz so you don't have to download the video file, but can preview it. In this raw OBS recording I WAS using a hacked client (no modules were enabled), however I can also try reproducing on pure Vanilla if you wish.

6) **A very detailed description of the issue.**
Whenever towering quickly, Most of the time I'm able to false flag the Fly A check and even get false kicked (I do this for most of the recording, but I think 00:03, 01:15, 01:27, 02:25, 03:25 and 04:10 are pretty good examples of this). 
 ​
I'm also able to periodically false flag Scaffold F by placing blocks on the ground quickly below me, but here I don't get false kicked and it doesn't false flag as frequently as Fly A (see 00:54 and 02:08).

**Comment by Nort721** [comment]
Hey there, seems like I don't manage to replicate the falses you showed in the video, I did implement a fix to Fly TypeA, but for the other stuff the client you were using was maybe bugging some packets?

also did you use a right click AutoClicker to place blocks for the Scaffold TypeF false?

**Comment by bG9sIHVyIGhvbW8** [comment]
> Hey there, seems like I don't manage to replicate the falses you showed in the video, I did implement a fix to Fly TypeA, but for the other stuff the client you were using was maybe bugging some packets?
> 
> also did you use a right click AutoClicker to place blocks for the Scaffold TypeF false?

I'm unsure if the client was modifying game mechanics, but then again I can try reproducing on pure Vanilla.

And no, I didn't use a autoclicker for right click, that was me right clicking legitimately.

**Comment by Nort721** [comment]
Implemented a fix for Fly TypeA and hopefully also for the Scaffold TypeF check in  Build 45, keeping this open so I come back for the reset later
