### ISSUE TITLE
GodsEye Settings Not Saving After Restart

### ISSUE THREAD

**Issue by spruill7716** [Nort721/GodsEye#377]
1) GodsEye Build 45
2) Paper #592
3) ProtocolLib v4.6.0

Having an issue where any commands I input such as '/godseye alerts',  '/godseye verbose', or any changes with '/godseye cp' not saving when the server restarts. I have to manually turn off verbose messages after each time to reduce chat spam.

**Comment by Nort721** [comment]
These cmmands are not meant to be saved, if you want config changes to be saved you need to make the changes in the config, in addition verbose messages do not enable automatically so you maybe mean the alerts which do not spam the chat

I you dont want alerts to enable automatically you need not remove the godseye.command.alerts permission from you or your grouo

**Comment by TehSteel** [comment]
Is there anything else that we can help with?
@spruill7716

**Comment by TehSteel** [comment]
Issue closed due inactivity
