### ISSUE TITLE
Slow Falling Pot -Kicked for fly,

### ISSUE THREAD

**Issue by Aflexboii** [Nort721/GodsEye#378]
A bug report/issue report should contain:

1) GodsEye version
2) Server Version+Fork: 1.16.5 (Spigot) -Not sure what fork is sorry!
3) ProtocolLib version: (Auto updated) - Set on whatever the current most updated version is for 1.16.5
4) Server log - Log does not show anything relating to godseye except for when the kick is performed: [19:43:25 INFO]: Player Console kicked Aflexboii for You have been kicked for hacking : GODSEYE CHEAT DETECTION.
5) https://ibb.co/9rTK8QW - What godseye displays ingame
6) When using slow fall pots, or getting a slow fall effect from shulkers in the end, Players recieve many false warnings and kicks resulting from it.

**Comment by Nort721** [comment]
For now, open checks.yml and disablw Fly TypeD

**Comment by Izibane** [comment]
disablw 
![why](https://user-images.githubusercontent.com/77923336/116550361-329c9880-a8e6-11eb-9181-aef89913f934.png)
