### ISSUE TITLE
GodsEye Check Issues

### ISSUE THREAD

**Issue by TheDejavu** [Nort721/GodsEye#381]
A bug report/issue report should contain:

1) GodsEye version - Build 45 HotGix-1
2) Server Version+Fork - Spigot 1.8.8
3) ProtocolLib version - 4.5.1
4) Server log - nothing to see
5) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster. - https://youtu.be/Wc9NyVeYLEQ
https://youtu.be/jpfvenSS0MY
6) A very detailed description of the issue
Speed TypeC is beeing false flagged when running + jumping.
Rest is in videos.

**Comment by Nort721** [comment]
There isn't much to do about the Knockback false positive until I finish the Velocity checks which will completely replace it, for the InventoryActions TypeA false positive I'm reverting to the old InventoryActions TypeA check is a temporary solution for until the recode is out
