### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by typecek123** [Nort721/GodsEye#382]
1) GodsEye version: Build 45 HotFix-1
2) Server Version+Fork: CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
3) ProtocolLib version: 4.6.0
4) Server log
https://pastebin.com/3G5u3N8Y
6) A very detailed description of the issue:
We use plugin MBedwars and when we join map, sometimes one or more players spawn into void and it bugs them and errors in console are spamming there and I see GodsEye written there in these errors. After some time it kicks player for cheats when he's bugged there in void.

**Comment by Nort721** [comment]
Will make sure to check that out, start with updating to the latest version and see if the error still happens
