### ISSUE TITLE
Login checks activation delay: X not working

### ISSUE THREAD

**Issue by AsP3X** [Nort721/GodsEye#383]
A bug report/issue report should contain:

GodsEye Build:     Build 45 HotFix 1
Server Version:     Paper-651-1.16.5
ProtoLib Version:  ProtocolLib v4.6.0

LOG: No log output of any kind

After changing the the Login delay and server restart the plugin still triggers after the default delay.
There is no way to change that at the moment.

**Comment by Nort721** [comment]
Please send a pastebin of your checks.yml here

**Comment by AsP3X** [comment]
https://pastebin.com/p0kB1e8z

**Comment by Nort721** [comment]
hey there, what do you mean by the plugin triggers? note that the plugin will load when you start the server always the same, the delay is how much time after the player logs in the checks starts to check him

**Comment by Nort721** [comment]
Got no response for the last question from the user, closing the ticket for inactivity, if you still in help with the issue contact us on discord and we will re-open this issue, or open a new issue ticket
