### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Pikaronga** [Nort721/GodsEye#384]
A bug report/issue report should contain:

https://pastebin.com/zcP5BDyi

1) GodsEye version
2) 1.16.5 PurPur
3) Latest dev
4) https://pastebin.com/zcP5BDyi
6) Randomly when users chat or just do anything this error appears. this specifically is when someone chats.

**Comment by Izibane** [comment]
nort didnt add @override to his chat packet listener
![792431299662839820](https://user-images.githubusercontent.com/77923336/119041886-b2c69300-b9a6-11eb-9258-998080f33328.png)
