### ISSUE TITLE
Dropping items fastly triggers TypeH BADPACKETS

### ISSUE THREAD

**Issue by parkerbryan** [Nort721/GodsEye#386]
1) GodsEye vBuild 46
2) MC version 1.16.5 git-Paper-704
3) ProtocolLib version v4.6.0
4) 
    Detection: BADPACKETS
    Type: TypeH
    TPS: 20.0
    Ping: 16
5) N/A
6)
If you hold down the key to drop an item (default Q), GodsEye will trigger for BADPACKETS, TypeH.
This was reported to me by a user, and I tested it myself with the same result. Disabling TypeH checks resolves the issue.
My client is Fabric with some UI mods (including OptiFine), not a lot going on. Have not yet confirmed if the other user is using vanilla or forge/fabric, I'll update when I know.

**Comment by parkerbryan** [comment]
Confirmed the other user is vanilla 1.16.5 client.

**Comment by Nort721** [comment]
Will make sure to check that out, for now disable BadPackets TypeH
