### ISSUE TITLE
Feature request. Fly setback position reset, when onground.

### ISSUE THREAD

**Issue by akosvr** [Nort721/GodsEye#387]
Just a feature request.

**Fly setback position reset, when onground.**
It would make the setback more accourate.

**Comment by Nort721** [comment]
You want the setback position to be set to the player's position when they are on ground

**Comment by akosvr** [comment]
Well only if the player is not cheating or not getting any flag for like 5 seconds. Just an idea, to make godseye better.

**Comment by Nort721** [comment]
> Well only if the player is not cheating or not getting any flag for like 5 seconds. Just an idea, to make godseye better.

sorry for taking a while to continue replying to this, that's already what the current system does, the amount of seconds is also configurable
