### ISSUE TITLE
Kick, while in spectator mode

### ISSUE THREAD

**Issue by LeNinjaHD** [Nort721/GodsEye#390]
A bug report/issue report should contain:

1) GodsEye version
Build 47
2) Server Version+Fork
paperspigot 1.8.8
3) ProtocolLib version
/
4) Server log
None
5) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster.
https://youtu.be/ujrRHPlYCkI
6) A very detailed description of the issue

If someone is using NoPitchLimit (You can spin you head infinitly), and someone is spectating them (GameMode 3 + Leftclick on player) they get kicked too.

**Comment by Nort721** [comment]
Whats wrong about it, you cheated, you got kicked, whats the problem here?

**Comment by LeNinjaHD** [comment]
The problem is, that if you spectate a player, you get kicked too.

**Comment by Nort721** [comment]
If you spectate without cheating you also get kicked?

**Comment by LeNinjaHD** [comment]
Yes
