### ISSUE TITLE
Timer TypeA and TypeB false flags when sprinting + clicking with a sword

### ISSUE THREAD

**Issue by itzpvp1235** [Nort721/GodsEye#392]
A bug report/issue report should contain:

1) GodsEye version = Build 48
2) Server Version+Fork = Paper 1.17
3) ProtocolLib version = 4.7.0
4) Server log = 
(No errors / warnings in console)

5) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster.
I posted it in discord https://discord.com/channels/533012305626136576/599887666573606923/869807070050914334

I cant upload files over 10mb on this thread so I cant attach it

6) A very detailed description of the issue
Timer TypeA and typeB will false flag every 0.5 seconds for some reason when sprint jumping while spamming right-click a sword / axe

**Comment by itzpvp1235** [comment]
sometimes, scaffold typeG and typeC also flag when you do this
idk why

**Comment by Nort721** [comment]
Hey there, as said in the last update GodsEye is not 1.17 ready yet which I find is probably the cause for these issues, none the less will make sure that these issues get fixed when we release the next 1.17 compatibility updates
