### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Godinhooo** [Nort721/GodsEye#393]
Hey, I found some bugs in the plugin
If you keep running (with speed potion)
and from time to time jump up, the anticheat accuses you

**Comment by Nort721** [comment]
Hey there,
The template was there for a reason, we need you to fill in the template information to be able to help you
Template:
A bug report/issue report should contain:

1) GodsEye version
2) Server Version+Fork
3) ProtocolLib version
4) Server log
5) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster.
6) A very detailed description of the issue

Please provide the information, also provide the check type that flags you, maybe a screenshot of the verbose notifications you get in chat

**Comment by Nort721** [comment]
Issue closed for lack of info
