### ISSUE TITLE
Missing checks

### ISSUE THREAD

**Issue by SteamJays** [Nort721/GodsEye#396]
1) Build 49
2) -
3) -
4) -
5) ![2021-08-09_19 33 00](https://user-images.githubusercontent.com/82319423/129474301-97c48484-e20a-4665-ba1d-3985ff57e095.png)
6) Missing XCarry, Jesus, Blink, AntiVoid checks

**Comment by Nort721** [comment]
Are you requesting for new checks to block these cheats?

**Comment by SteamJays** [comment]
Yes
