### ISSUE TITLE
GodsEye b49 bypass | Clip and AirJump

### ISSUE THREAD

**Issue by Regomy** [Nort721/GodsEye#397]
A bug report/issue report should contain:

1) GodsEye AntiCheat | Advanced Detection Build 49 HotFix-1
2) Spigot 1.8.9
3) 4.5.1
4) No arguments, please check my video.
5) https://youtu.be/pwCE5Gu3rQg
6) AirJump | Jumps on 2 blocks up // NoClip - No arguments

**Comment by Nort721** [comment]
You literally got flagged more then 20 times in the video

You got detected so much
