### ISSUE TITLE
can i get an reinboursement?

### ISSUE THREAD

**Issue by jujorito** [Nort721/GodsEye#398]
A bug report/issue report should contain:

1) GodsEye version
2) Server Version+Fork
3) ProtocolLib version
4) Server log
5) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster.
6) A very detailed description of the issue

**Comment by Officiated** [comment]
Is there a reason you would like a reimbursement? If you are experiencing and issues we highly recommend getting in contact with our support team, you can do so by visiting our discord here: https://discord.gg/gHJ8Cjx

**Comment by Nort721** [comment]
handled on discord
