### ISSUE TITLE
False flaggin Drag clicking

### ISSUE THREAD

**Issue by LeNinjaHD** [Nort721/GodsEye#402]
A bug report/issue report should contain:

1) GodsEye version
Build 49 Hotfix-1
2) Server Version+Fork
paperspigot 1.8.8
3) ProtocolLib version
The one from the spigot link from the godseye page
4) Server log
-
5) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster.
https://youtu.be/yjrFUAiwvLU
6) A very detailed description of the issue
You get false flagged when drag clicking. (max cps is 55 as seen in the beginning)

**Comment by Nort721** [comment]
AutoClicker TypeA is a double clicking check, if you want to allow double clicking on your server therefore allow butterfly clicking and drag clicking, you'll need to disable AutoClicker TypeA and increase the max cps from 20 to the amount you want to allow
