### ISSUE TITLE
Scaffold, buildReach, FastStairs, NoWeb, Jesus (LiquidWalk)

### ISSUE THREAD

**Issue by Regomy** [Nort721/GodsEye#403]
A bug report/issue report should contain:

1) GodsEye AntiCheat | Advanced Detection Build 49 HotFix-1
2) git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
3) ProtocolLib v4.5.1
4) -
5) https://youtu.be/VRX26ByAA50
6) LiquidBounce : Scaffold, buildReach, FastStairs, NoWeb, Jesus (LiquidWalk), speed
( Speed settings: 

    "CustomSpeed": 0.25,
    "CustomY": 0.26,
    "CustomTimer": 1.04,
    "CustomStrafe": true,
    "CustomResetXZ": false,
    "CustomResetY": false,
)

**Comment by Nort721** [comment]
Hey there, give a test to these cheats on our official test server and let us know what you find
