### ISSUE TITLE
Multiple errors with Gods Eye plugin.

### ISSUE THREAD

**Issue by LpDeath** [Nort721/GodsEye#407]
Multiple errors with this plugin.

1) godseye-build-49-hotfix-2
2) Patina version git-Paper-"5e0fe70" (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT)
3) ProtocolLib 4.7.0
4) https://paste.helpch.at/pilafemitu.sql
5) I don't see the need for a video, it's just that some kind of error appears every time the player restarts and the console clutters me up a lot.
6) sorry if my english is bad, crawling google translator. in general, I explain what happened: every time a player restarts, 2 errors appear. anti-cheat seems to work, but I really do not like these errors, they terribly clutter up the console.

**Comment by Nort721** [comment]
Are you sure you are using Build 49 HotFix-2?

**Comment by Nort721** [comment]
Found the issue, should be fixed for next version
