### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by KahpotVanilla** [Nort721/GodsEye#412]
A bug report/issue report should contain:

1) GodsEye version: Build 49 HotFix-2
2) Server Version+Fork: 1.17.1, PaperMC
3) ProtocolLib version: 4.7.0
4) Server log: https://pastebin.com/1CPKj3Un
5) A very detailed description of the issue: It's just spamming the console when someone makes a wrong packet move I guess.

**Comment by Nort721** [comment]
are you sure you were using GodsEye Build 49 HotFix-2? not an earlier one?

**Comment by KahpotVanilla** [comment]
> 2

Yes, I am.

**Comment by Nort721** [comment]
Found the issue, should be fixed for next version
