### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Pikaronga** [Nort721/GodsEye#416]
[A bug report/issue report should contain:

1) Build 49 HotFix-3
2) 1.17.1 Purpur
3) ProtoclLib4.7.0
4) https://pastebin.com/EFFhgz3j

**Comment by SadRusty** [comment]
I have same error.

**Comment by Nort721** [comment]
Well I've done some research about this error and it doesn't make a lot of sense, seems like a ProtocoLlib error, I've implemented some changes that might hopefully prevent it from happening in the future, the patch will be out in the next hotfix
