### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by ProtoGhost** [Nort721/GodsEye#418]
A bug report/issue report should contain:

GodsEye AntiCheat | Advanced Detection Build 49 HotFix-3
ProtocolLib v4.7.0
paper 1.8.8
This server is running CraftBukkit version git-Spigot-6abac0c-9935adc (MC: 1.8.8)
[serverlog](https://github.com/Nort721/GodsEye/files/7532228/serverlog.txt)

**Comment by Nort721** [comment]
I've worked on some patches, this should be fixed in the next version
