### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Pikaronga** [Nort721/GodsEye#421]
A bug report/issue report should contain:

1) godseyeBuild 49 HotFix-3, sync 2.1.2-BETA
2) velocity 3.0.1 
3) Protocolize - ProtocolLib for BungeeCord / Waterfall / Velocity 2.0.1
5) https://pastebin.com/ZPcQV53k

**Comment by Nort721** [comment]
Hey there, this error seems to be a GodsEyeSync error, not an error in GodsEye
GodsEyeSync is a completely separate third-party plugin which means its also not made by me, so you should report the error to the GodsEyeSync developer, for that you can message him privately on SpigotMC, or use the GodsEye-Sync support channel in the GodsEye discord server
GodsEyeSync spigot page: https://www.spigotmc.org/resources/godseyesync-data-synchronization-and-bungeecord-velocity-alerts.78815/
Discord of the GodsEyeSync developer: GoodTimes14#4416
