### ISSUE TITLE
console errors spam

### ISSUE THREAD

**Issue by ProtoGhost** [Nort721/GodsEye#423]
A bug report/issue report should contain:

GodsEye AntiCheat | Advanced Detection Build 49 HotFix-3
ProtocolLib v4.7.0
paper 1.8.8
This server is running CraftBukkit version git-Spigot-6abac0c-9935adc (MC: 1.8.8)
[Errors] https://pastebin.com/LV4RpYs8

**Comment by Nort721** [comment]
Seems like a pretty weird error, seems like a bug in ProtocolLib, I've implemented some patches in GodsEye to hopefully prevent it from happening, so it hopefully should be fixed for the next version
Unfortunately, I can't do much about a ProtocolLib bug
