### ISSUE TITLE
Console spam error

### ISSUE THREAD

**Issue by MrLiam2614** [Nort721/GodsEye#424]
A bug report/issue report should contain:

1) GodsEye version -> Build 49 HotFix-3
2) Server Version+Fork -> Paper 1.17
3) ProtocolLib version -> 4.7.0
4) Server log -> https://pastebin.com/rF1SfNvb

The console is full of this, i just can't read the console because of the spamm

**Comment by Nort721** [comment]
Please submit errors using pastebinl.com

**Comment by Nort721** [comment]
Are you sure you are running this version of GodsEye?

**Comment by ProtoGhost** [comment]
yes im sure

**Comment by MrLiam2614** [comment]
> Are you sure you are running this version of GodsEye?

yes, i'm running the last version of GodsEye (now Build49 HotFix-5)

**Comment by 0xntpower** [comment]
Fixed in the latest version
