### ISSUE TITLE
bypassing ping spoof 

### ISSUE THREAD

**Issue by ProtoGhost** [Nort721/GodsEye#426]
A bug report/issue report should contain:

GodsEye AntiCheat | Advanced Detection Build 49 HotFix-3
ProtocolLib v4.7.0
paper 1.8.8
This server is running CraftBukkit version git-Spigot-6abac0c-9935adc (MC: 1.8.8)
FDP client bypassing pingspoof 
https://getfdp.today/

**Comment by Nort721** [comment]
Answered on discord - PingSpoof detection doesn't matter much since 99% of GodsEye systems are not dependent on ping therefore pingspoof wouldn't give the cheater any advantage or ability to bypass checks
