### ISSUE TITLE
[GodsEye] Unhandled exception occured in onPacketReceiving(PacketEvent) for GodsEye java.lang.NullPointerException

### ISSUE THREAD

**Issue by ProtoGhost** [Nort721/GodsEye#427]
A bug report/issue report should contain:

GodsEye AntiCheat | Advanced Detection Build 49 HotFix-5
ProtocolLib v4.7.0
paper 1.8.8
This server is running CraftBukkit version git-Spigot-6abac0c-9935adc (MC: 1.8.8)
https://mclo.gs/TcO2Vih

**Comment by Nort721** [comment]
Hey there, this issue should not appear in the current latest version of GodsEye, if it still appears even when you update, let us know and we will re-check the issue
