### ISSUE TITLE
Bug: "The server you were previously on went down, you have been connected to a fallback server"

### ISSUE THREAD

**Issue by MrLiam2614** [Nort721/GodsEye#428]
A bug report/issue report should contain:

1) GodsEye version -> Build 49 HotFix-5
2) Server Version+Fork -> Paper 1.17.1
3) ProtocolLib version -> 4.7.0
4) Server log -> Nothing on the log

I already tried removing godseye and without that all is just working fine,
The problem is the tab completer (i think), for example if i type "//cyl" and then add a " " the server kicks me with: "The server you were previously on went down, you have been connected to a fallback server".

**Comment by ItzGuy** [comment]
//cyl is worldedit report it to worldedit

**Comment by MrLiam2614** [comment]
> //cyl is worldedit report it to worldedit

Yes but, if i remove godseye all is working, that's a problem from the last update i did for godseye:/

**Comment by Nort721** [comment]
we found what causes the issue and are releasing a fix in the next version, for now, use any build before 49 HotFix-3, thanks for reporting

**Comment by Nort721** [comment]
This issuw has been fixed in the latest version of GodsEye, if any of you are still having it in the latest version, be sure to let me know
