### ISSUE TITLE
Movement false check

### ISSUE THREAD

**Issue by QluxpEL** [Nort721/GodsEye#445]
1) Build 50 [test Server]
2) No idea, i was in official test server
3) No idea, i was in official test server
4) No acces to it.
5) Video proof ment https://youtu.be/_U6b80pp0vU
6) If your playing on version 1.13+ where is better swiming when your reach an block gods eye will start glitching you

**Comment by Nort721** [comment]
Hey there, this is most likely not GodsEye causing this issue, its probably some weird glitch in Minecraft or the client you are using, could also be a bug in the connection between the 1.8 server and your 1.18 client

**Comment by Nort721** [comment]
closed because this bug is most likely not caused by GodsEye
