### ISSUE TITLE
False movement flag

### ISSUE THREAD

**Issue by QluxpEL** [Nort721/GodsEye#447]
1) Build 50 [test Server]
2) No idea, i was in official test server
3) No idea, i was in official test server
4) No acces to it.
5) Video proof ment https://youtu.be/bgGTsY4dOTc
6) If your sneaking and jumping in a same time Gods Eye will think your using some hacks

**Comment by Nort721** [comment]
What Minecraft version your client is on? also are you using any mods? from the video it seems you do not slow down from sneaking which is impossible without NoSlow cheats

**Comment by 0xntpower** [comment]
closed for lack of info
