### ISSUE TITLE
BadPackets false flag

### ISSUE THREAD

**Issue by QluxpEL** [Nort721/GodsEye#448]
1) Build 50 [test Server]
2) No idea, i was in official test server
3) No idea, i was in official test server
4) No acces to it.
5) Video proof ment https://youtu.be/GTR9L86GPNA
6) If your lowground andbreaking the bed gods eye will think your using hacks

**Comment by Nort721** [comment]
Thanks for the report, this false is pretty much the same as in issue #444, which is why I am closing it here under the duplicate tag and the issue itself will be handeled in issue #444, next time if you want to add info about an issue you can just comment it under the initial issue
