### ISSUE TITLE
Velocity fals flag

### ISSUE THREAD

**Issue by QluxpEL** [Nort721/GodsEye#449]
1) Build 50 [test Server]
2) No idea, i was in official test server
3) No idea, i was in official test server
4) No acces to it.
5) Video proof ment https://youtu.be/SiNBu5GD-hU
6) If your shot your self with bow and you behind cobweb you get false flagged

**Comment by Nort721** [comment]
I Implemented a fix attempt for the next version, this issue is already fully patched in the GodsEye recode as it has the new collision system we have developed, this system doesn't exist in current GodsEye, but I'll attempt setting up something temporary for until the recode releases
