### ISSUE TITLE
False movement flag

### ISSUE THREAD

**Issue by QluxpEL** [Nort721/GodsEye#450]
1) Build 50 [test Server]
2) No idea, i was in official test server
3) No idea, i was in official test server
4) No acces to it.
5) Video proof ment https://youtu.be/3ULFg38bQbo 
6) If your sneaking and jumping and above you us block your get flagged

**Comment by Nort721** [comment]
Thanks for the report, however this report seems to be a duplicate of issue #441, so this specific issue is closed under the duplicate tag
