### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by GAMERFORCE99** [Nort721/GodsEye#453]
A bug report/issue report should contain:

1) GodsEye version build 51
2) Server Version+Fork
3) ProtocolLib version 4.8.0
4) Server log
5) We recommend sending a video/screenshot of the issue if possible, so we would be able to fix it faster.
6) A very detailed description of the issue
the errors- https://paste.gg/p/anonymous/6a6332a13044440696402fe7ebe6854c/revisions

**Comment by ProtoGhost** [comment]
don't mind this thing will never be fixed you got scammed
