### ISSUE TITLE
MCMMO support

### ISSUE THREAD

**Issue by harry2512tea** [Nort721/GodsEye#56]
A bug report/issue report should contain:

1) Server Version+Fork: N/A
2) ProtocolLib version: N/A
3) Server log: N/A
4) We recommend sending a video/a screenshot of the issue if possible, so we would be able to fix it faster: N/A
5) A very detailed description of the issue: possibly add MCMMO support, would allow servers to be more versatile while maintaining security

**Comment by Nort721** [comment]
gonna look into the MCMMO API in the next updates

**Comment by Nort721** [comment]
In one of the last update I have added methods to the api that would allow to adapt and change checks to support mcmmo
